Libc++ r249800 breaks labs(3).  Revert to working revisions for now.
$ if [ "$CXX" = "clang++" ]; then (cd libcxxabi/lib && env CXX="clang++ -I ../../libcxx/include" sh buildit); fi
+clang++ -I ../../libcxx/include -c -g -O3 -fPIC -std=c++11 -stdlib=libc++ -fstrict-aliasing -Wstrict-aliasing=2 -Wsign-conversion -Wshadow -Wconversion -Wunused-variable -Wmissing-field-initializers -Wchar-subscripts -Wmismatched-tags -Wmissing-braces -Wshorten-64-to-32 -Wsign-compare -Wstrict-aliasing=2 -Wstrict-overflow=4 -Wunused-parameter -Wnewline-eof -I../include ../src/abort_message.cpp
In file included from ../src/abort_message.cpp:10:
../../libcxx/include/stdlib.h:114:82: error: use of undeclared identifier
      'labs'; did you mean 'abs'?
  ...long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                                     ^
../../libcxx/include/stdlib.h:114:44: note: 'abs' declared here
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT ...
                                           ^
../../libcxx/include/stdlib.h:116:81: error: use of undeclared identifier
      'llabs'
  ...long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                                    ^
../../libcxx/include/stdlib.h:119:35: error: unknown type name 'ldiv_t'
inline _LIBCPP_INLINE_VISIBILITY  ldiv_t div(     long __x,      long __...
                                  ^
../../libcxx/include/stdlib.h:119:95: error: use of undeclared identifier
      'ldiv'; did you mean 'div'?
  ...ldiv_t div(     long __x,      long __y) _NOEXCEPT {return  ldiv(__x, __...
                                                                 ^
../../libcxx/include/stdlib.h:119:42: note: 'div' declared here
inline _LIBCPP_INLINE_VISIBILITY  ldiv_t div(     long __x,      long __...
                                         ^
../../libcxx/include/stdlib.h:121:34: error: unknown type name 'lldiv_t'
inline _LIBCPP_INLINE_VISIBILITY lldiv_t div(long long __x, long long __...
                                 ^
../../libcxx/include/stdlib.h:121:94: error: use of undeclared identifier
      'lldiv'
  ...lldiv_t div(long long __x, long long __y) _NOEXCEPT {return lldiv(__x, _...
                                                                 ^
../src/abort_message.cpp:43:14: error: use of undeclared identifier 'stderr'
    vfprintf(stderr, format, list);
             ^
../src/abort_message.cpp:45:13: error: use of undeclared identifier 'stderr'
    fprintf(stderr, "\n");
            ^
../src/abort_message.cpp:78:5: error: use of undeclared identifier 'abort'
    abort();
    ^
9 errors generated.